django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from polls import urls as polls_urls

app_name = 'polls'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^polls/', include('polls.urls')) 정적으로 표현 ( str으로 ), 장고urls에 내장되어 있는 include 함수 !!
    url(r'^polls/', include(polls_urls))  # 동적 표현
]

django_app/polls/urls.py
from django.conf.urls import url

from . import views  # 자기자신이 속한 페키지 표현

# from polls import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail,
        name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_app/polls/models.py
import datetime
from django.utils import timezone

from django.db import models


class Question(models.Model):
    question_text = models.CharField('질문내용', max_length=200)
    pub_date = models.DateTimeField('발행일자')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.short_description = '최근발행여부'
    was_published_recently.boolean = True
    # was_published_recently.admin_order_field =


class Choice(models.Model):
    question = models.ForeignKey(
        Question,
        verbose_name='해당질문',
        on_delete=models.CASCADE
    )
    choice_text = models.CharField('선택내용', max_length=200)
    votes = models.IntegerField('총 투표수', default=0)

    # migrations 하려면 모델링을 해야한다.

django_app/polls/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Question, Choice


def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html') + HttpResponse 이 과정을 줄인 게 render 함수
    # get_list_or_404를 사용한 경우
    latest_question_list = get_list_or_404(Question.objects.order_by('-pub_date')[:5])
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    # question_id가 pk인 Question객체를 가져와
    # context라는 이름을 가진 dict에 'question'이라는 키 값으로 위 변수를 전달
    # 이후 'polls/detail.html'과 context를 렌더한 결과를 리턴

    # question.choice_set = Choice.objects.filter(question=question)

    # polls/detail에서 해당 question의 question_text를 출력
    # try:
    #     question = Question.objects.get(pk=question_id)  # get(쿼리셋에서 어떤 것을 집어오는 것)함수는 pk값을 받는다 !
    # except Question.DoesNotExist as e:
    #     raise Http404('Question does not exist')
    question = get_object_or_404(Question, pk=question_id)  # 오류 검사 한 줄로 줄여쓴 것
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    # detail.html파일을 약간 수정해서 results.html을 만들고
    # 질문에 대한 모든 선택사항의 선택수(votes)를 출력
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    # detail.html내부
    # question을 출력
    # 해당 question의 모든 choice들 (question.choice_set.all) 출력
    # loop돌며 각 choice의 제목과 votes를 출력

    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    # request의 method가 POST방식일 때,
    # 전달받은 데이터 중 'choice'키에 해당하는 값을
    # HttpResponse에 적절히 돌려준다

    # choice키에 해당하는 Choice인스턴스의 vote값을 1증가시키고
    # 데이터베이스에 변경사항을 반영
    # 이후  results페이지로 redirect
    if request.method == 'POST':
        date = request.POST
        try:
            choice_id = date['choice']

            choice = Choice.objects.get(id=choice_id)
            choice.votes += 1
            choice.save()
            # return HttpResponse('Choice is %s' % choice_id)

            # 이후 results페이지로 redirect
            return redirect('polls:results', question_id)
        except (KeyError, Choice.DoesNotExist):
            # message 프레임워크를 사용
            # 지금 몰라도 됨
            # request에 메시지를 저장해놓고 해당 request에 대한
            # response를 돌려줄 때 메시지를 담아 보낸다
            messages.add_message(
                request,
                messages.ERROR,
                "You didn't select a choice",
            )
            return redirect('polls:detail', question_id)
    else:
        return HttpResponse("You're voting on question %s." % question_id)

django_app/templates/polls/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <title>{% block title %}Polls Application{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

django_app/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block title %}Polls Detail{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    {% if messages %}
        {% for message in messages %}
            <p><strong>{{ message }}</strong></p>
        {% endfor %}
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice-{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br/>
        {% endfor %}
        <button type="submit">Vote</button>
    </form>

{% endblock %}


{# id값이랑 for값이랑 일치해야돰#}
{#forloop counter for문을 돌면서 자신이 몇번째 값인지 세어준다. 여기서는 for문 돌면서 값이 1씩 증가#}

django_app/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %}Polls Index{% endblock %}

{% block content %}


    {% if latest_question_list %}
        {#    # 변수나 쿼리셋이 왔거나 안왔거나 (조건) 했을 때#}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.pk %}">
                    {#        이거랑 url링크랑 차이#}
                    {{ question.question_text }}
                </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

django_app/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block title %}Polls Results{% endblock %}
{% block content %}
    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                <span>{{ choice.choice_text }} : {{ choice.votes }}</span>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again!</a>

{% endblock %}